### PR TITLE
Added functionality to load json from URL

### LINKED ISSUE #5: Load data file from a URL
**Is your feature request related to a problem? Please describe.**
Currently, the CLI only supports loading data from a local file. Some data files may be hosted online, or on a local server.

**Describe the solution you'd like**
The `--data` flag should be able to handle URLs and directly load a file from there.

### PR DESCRIPTION
**Pull request by mauriceackel**
**Parent issue** 

Closes #5 

**Technical implementation details**

Added node-fetch lib to fetch JSON data from URLs, depending on the prefix of the `filePath` variable.

### CODE REVIEW

**Comment by mauriceackel** [comment]
Hey peeps, guess I should have discussed some implementation details with you first 😓. Anyways, if you have recommendations for changing the implementation, please let me know 😄

Regarding the tests: I added some negative tests but no positive tests as I was not sure about the best way to do this (i.e. we need a test file hosted somewhere)

**Review by 255kb — CHANGES_REQUESTED** [review]
@mauriceackel thank you for the contribution, that was fast 😆 
It's true that our preferred way of contributing is to first assign the issue (to avoid any parallel work on the same task), and then discuss the implementation a little bit. But it's ok!

Here are some remarks:
- I like node fetch, but could you please use axios which is already added as a dev dependency and used in the tests (and thus move it in the `dependencies`)? I would like to reduce the dependencies at a minimum. Also, after adding @types/node-fetch, there are some issues with Typescript. I think axios will work a little bit better.
- To add a "positive" test, you can use this data file https://github.com/mockoon/cli/blob/main/test/data/sample-data.json. It's used in the tests and shouldn't change. So, it's safe to use it.

**Comment by mauriceackel** [comment]
@255kb On it 🔥

**Comment by 255kb** [comment]
@mauriceackel When you finish could you also squash your commits? Thank you! 🚀

**Comment by 255kb** [comment]
@mauriceackel I forgot, could you comment on each of the issues you are working on, so I can assign them to you, otherwise I cannot 👍

**Comment by mauriceackel** [comment]
@255kb Yeah, I was a bit unsure about this as I kinda like it to have the traceability at least in the PR. There is this GitHub function where you can squash&merge when clicking on the merge button. Have you considered using it?

**Comment by 255kb** [comment]
Yeah I know this option. But I don't really like the "new" commit message resulting from this, with all the commit titles stacked under each other. It usually result in something like this: 
```
Feature XXX
fix
fix 
fix 
fix 
``` 
🤣

**Comment by 255kb** [comment]
But you are right, I will use it, after all, i's good enough and automatic.

**Comment by 255kb** [comment]
Sorry, the correct URL for the sample data file is: https://raw.githubusercontent.com/mockoon/cli/main/test/data/sample-data.json

**Review by 255kb — APPROVED** [review]
Thank you, it's perfect :)

**Pull request merged**
